package dev.chiraitori.mizuki.data.repository

import android.content.Context
import android.content.SharedPreferences
import dev.chiraitori.mizuki.core.model.AudioFormat
import dev.chiraitori.mizuki.core.model.DownloadConfig
import dev.chiraitori.mizuki.core.model.DownloadType
import dev.chiraitori.mizuki.core.model.VideoResolution
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class ThemeMode(val label: String) {
    SYSTEM("Theo hệ thống"),
    LIGHT("Giao diện sáng"),
    DARK("Giao diện tối"),
    AMOLED("Tối thuần (AMOLED Đen)")
}

data class AppPreferences(
    val downloadConfig: DownloadConfig = DownloadConfig(),
    val themeMode: ThemeMode = ThemeMode.SYSTEM,
    val dynamicColor: Boolean = true,
    val language: String = "SYSTEM",
    val videoContainer: String = "ANY", // ANY, MP4, MKV, WEBM
    val videoCodec: String = "ANY", // ANY, H264, VP9, AV1
    val audioBitrate: String = "320k",
    val keepOriginalAudio: Boolean = false,
    val subLangs: String = "vi,en,all",
    val subFormat: String = "srt",
    val autoGeneratedSubs: Boolean = true,
    val maxConcurrentDownloads: Int = 3,
    val rateLimit: String = "", // e.g. "5M", "2M", "1M"
    val autoRetry: Boolean = true,
    val retryCount: Int = 3,
    val proxyUrl: String = "",
    val customUserAgent: String = "",
    val extractorArgs: String = "",
    val forceIpv4: Boolean = false,
    val playlistSubfolder: Boolean = true,
    val overwriteExisting: Boolean = false,
    val verboseLogging: Boolean = false,
    val updateChannel: String = "STABLE", // STABLE, NIGHTLY, MASTER
    val restrictFilenames: Boolean = false,
    val useDownloadArchive: Boolean = false,
    val sponsorBlockCategories: String = "sponsor,selfpromo,intro,outro",
    val keepSubtitleFiles: Boolean = false,
    val privateMode: Boolean = false,
    val separateAudioDir: String? = null
)

class SettingsRepository private constructor(context: Context) {

    private val prefs: SharedPreferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    private val _appPrefsFlow = MutableStateFlow(loadAppPreferences())
    val appPrefsFlow = _appPrefsFlow.asStateFlow()

    private val _setupCompletedFlow = MutableStateFlow(prefs.getBoolean(KEY_SETUP_COMPLETED, false))
    val setupCompletedFlow = _setupCompletedFlow.asStateFlow()

    val configFlow = MutableStateFlow(loadConfig())

    fun loadConfig(): DownloadConfig {
        return DownloadConfig(
            type = try {
                DownloadType.valueOf(prefs.getString(KEY_TYPE, DownloadType.VIDEO.name) ?: DownloadType.VIDEO.name)
            } catch (_: Exception) {
                DownloadType.VIDEO
            },
            videoResolution = try {
                VideoResolution.valueOf(prefs.getString(KEY_RES, VideoResolution.BEST.name) ?: VideoResolution.BEST.name)
            } catch (_: Exception) {
                VideoResolution.BEST
            },
            audioFormat = try {
                AudioFormat.valueOf(prefs.getString(KEY_AUDIO_FMT, AudioFormat.MP3.name) ?: AudioFormat.MP3.name)
            } catch (_: Exception) {
                AudioFormat.MP3
            },
            embedThumbnail = prefs.getBoolean(KEY_EMBED_THUMB, true),
            embedSubtitles = prefs.getBoolean(KEY_EMBED_SUBS, false),
            embedMetadata = prefs.getBoolean(KEY_EMBED_META, true),
            cropArtworkSquare = prefs.getBoolean(KEY_CROP_ARTWORK, false),
            useAria2c = prefs.getBoolean(KEY_USE_ARIA2C, true),
            aria2cConnections = prefs.getInt(KEY_ARIA2C_CONNS, 16),
            customArgs = prefs.getString(KEY_CUSTOM_ARGS, "") ?: "",
            outputTemplate = prefs.getString(KEY_OUT_TEMPLATE, "%(title)s.%(ext)s") ?: "%(title)s.%(ext)s",
            customOutDir = prefs.getString(KEY_OUT_DIR, null),
            cookiesFilePath = prefs.getString(KEY_COOKIES_PATH, null),
            wifiOnly = prefs.getBoolean(KEY_WIFI_ONLY, false),
            removeSponsorSegments = prefs.getBoolean(KEY_SPONSORBLOCK, false),
            sponsorBlockCategories = prefs.getString(KEY_SPONSORBLOCK_CATS, "sponsor,selfpromo,intro,outro") ?: "sponsor,selfpromo,intro,outro",
            restrictFilenames = prefs.getBoolean(KEY_RESTRICT_FILENAMES, false),
            useDownloadArchive = prefs.getBoolean(KEY_DOWNLOAD_ARCHIVE, false),
            keepSubtitleFiles = prefs.getBoolean(KEY_KEEP_SUB_FILES, false),
            privateMode = prefs.getBoolean(KEY_PRIVATE_MODE, false),
            separateAudioDir = prefs.getString(KEY_SEPARATE_AUDIO_DIR, null)
        )
    }

    fun loadAppPreferences(): AppPreferences {
        val config = loadConfig()
        return AppPreferences(
            downloadConfig = config,
            themeMode = try {
                ThemeMode.valueOf(prefs.getString(KEY_THEME_MODE, ThemeMode.SYSTEM.name) ?: ThemeMode.SYSTEM.name)
            } catch (_: Exception) {
                ThemeMode.SYSTEM
            },
            dynamicColor = prefs.getBoolean(KEY_DYNAMIC_COLOR, true),
            language = prefs.getString(KEY_LANG, "SYSTEM") ?: "SYSTEM",
            videoContainer = prefs.getString(KEY_VIDEO_CONTAINER, "ANY") ?: "ANY",
            videoCodec = prefs.getString(KEY_VIDEO_CODEC, "ANY") ?: "ANY",
            audioBitrate = prefs.getString(KEY_AUDIO_BITRATE, "320k") ?: "320k",
            keepOriginalAudio = prefs.getBoolean(KEY_KEEP_ORIG_AUDIO, false),
            subLangs = prefs.getString(KEY_SUB_LANGS, "vi,en,all") ?: "vi,en,all",
            subFormat = prefs.getString(KEY_SUB_FORMAT, "srt") ?: "srt",
            autoGeneratedSubs = prefs.getBoolean(KEY_AUTO_GEN_SUBS, true),
            maxConcurrentDownloads = prefs.getInt(KEY_MAX_CONCURRENT, 3),
            rateLimit = prefs.getString(KEY_RATE_LIMIT, "") ?: "",
            autoRetry = prefs.getBoolean(KEY_AUTO_RETRY, true),
            retryCount = prefs.getInt(KEY_RETRY_COUNT, 3),
            proxyUrl = prefs.getString(KEY_PROXY_URL, "") ?: "",
            customUserAgent = prefs.getString(KEY_CUSTOM_UA, "") ?: "",
            extractorArgs = prefs.getString(KEY_EXTRACTOR_ARGS, "") ?: "",
            forceIpv4 = prefs.getBoolean(KEY_FORCE_IPV4, false),
            playlistSubfolder = prefs.getBoolean(KEY_PLAYLIST_SUBFOLDER, true),
            overwriteExisting = prefs.getBoolean(KEY_OVERWRITE, false),
            verboseLogging = prefs.getBoolean(KEY_VERBOSE_LOG, false),
            updateChannel = prefs.getString(KEY_UPDATE_CHANNEL, "STABLE") ?: "STABLE",
            restrictFilenames = prefs.getBoolean(KEY_RESTRICT_FILENAMES, false),
            useDownloadArchive = prefs.getBoolean(KEY_DOWNLOAD_ARCHIVE, false),
            sponsorBlockCategories = prefs.getString(KEY_SPONSORBLOCK_CATS, "sponsor,selfpromo,intro,outro") ?: "sponsor,selfpromo,intro,outro",
            keepSubtitleFiles = prefs.getBoolean(KEY_KEEP_SUB_FILES, false),
            privateMode = prefs.getBoolean(KEY_PRIVATE_MODE, false),
            separateAudioDir = prefs.getString(KEY_SEPARATE_AUDIO_DIR, null)
        )
    }

    fun updateConfig(config: DownloadConfig) {
        prefs.edit().apply {
            putString(KEY_TYPE, config.type.name)
            putString(KEY_RES, config.videoResolution.name)
            putString(KEY_AUDIO_FMT, config.audioFormat.name)
            putBoolean(KEY_EMBED_THUMB, config.embedThumbnail)
            putBoolean(KEY_EMBED_SUBS, config.embedSubtitles)
            putBoolean(KEY_EMBED_META, config.embedMetadata)
            putBoolean(KEY_CROP_ARTWORK, config.cropArtworkSquare)
            putBoolean(KEY_USE_ARIA2C, config.useAria2c)
            putInt(KEY_ARIA2C_CONNS, config.aria2cConnections)
            putString(KEY_CUSTOM_ARGS, config.customArgs)
            putString(KEY_OUT_TEMPLATE, config.outputTemplate)
            putString(KEY_OUT_DIR, config.customOutDir)
            putString(KEY_COOKIES_PATH, config.cookiesFilePath)
            putBoolean(KEY_WIFI_ONLY, config.wifiOnly)
            putBoolean(KEY_SPONSORBLOCK, config.removeSponsorSegments)
            putString(KEY_SPONSORBLOCK_CATS, config.sponsorBlockCategories)
            putBoolean(KEY_RESTRICT_FILENAMES, config.restrictFilenames)
            putBoolean(KEY_DOWNLOAD_ARCHIVE, config.useDownloadArchive)
            putBoolean(KEY_KEEP_SUB_FILES, config.keepSubtitleFiles)
            putBoolean(KEY_PRIVATE_MODE, config.privateMode)
            putString(KEY_SEPARATE_AUDIO_DIR, config.separateAudioDir)
            apply()
        }
        configFlow.value = config
        _appPrefsFlow.value = loadAppPreferences()
    }

    fun updateAppPreferences(appPrefs: AppPreferences) {
        updateConfig(appPrefs.downloadConfig)
        prefs.edit().apply {
            putString(KEY_THEME_MODE, appPrefs.themeMode.name)
            putBoolean(KEY_DYNAMIC_COLOR, appPrefs.dynamicColor)
            putString(KEY_LANG, appPrefs.language)
            putString(KEY_VIDEO_CONTAINER, appPrefs.videoContainer)
            putString(KEY_VIDEO_CODEC, appPrefs.videoCodec)
            putString(KEY_AUDIO_BITRATE, appPrefs.audioBitrate)
            putBoolean(KEY_KEEP_ORIG_AUDIO, appPrefs.keepOriginalAudio)
            putString(KEY_SUB_LANGS, appPrefs.subLangs)
            putString(KEY_SUB_FORMAT, appPrefs.subFormat)
            putBoolean(KEY_AUTO_GEN_SUBS, appPrefs.autoGeneratedSubs)
            putInt(KEY_MAX_CONCURRENT, appPrefs.maxConcurrentDownloads)
            putString(KEY_RATE_LIMIT, appPrefs.rateLimit)
            putBoolean(KEY_AUTO_RETRY, appPrefs.autoRetry)
            putInt(KEY_RETRY_COUNT, appPrefs.retryCount)
            putString(KEY_PROXY_URL, appPrefs.proxyUrl)
            putString(KEY_CUSTOM_UA, appPrefs.customUserAgent)
            putString(KEY_EXTRACTOR_ARGS, appPrefs.extractorArgs)
            putBoolean(KEY_FORCE_IPV4, appPrefs.forceIpv4)
            putBoolean(KEY_PLAYLIST_SUBFOLDER, appPrefs.playlistSubfolder)
            putBoolean(KEY_OVERWRITE, appPrefs.overwriteExisting)
            putBoolean(KEY_VERBOSE_LOG, appPrefs.verboseLogging)
            putString(KEY_UPDATE_CHANNEL, appPrefs.updateChannel)
            putBoolean(KEY_RESTRICT_FILENAMES, appPrefs.restrictFilenames)
            putBoolean(KEY_DOWNLOAD_ARCHIVE, appPrefs.useDownloadArchive)
            putString(KEY_SPONSORBLOCK_CATS, appPrefs.sponsorBlockCategories)
            putBoolean(KEY_KEEP_SUB_FILES, appPrefs.keepSubtitleFiles)
            putBoolean(KEY_PRIVATE_MODE, appPrefs.privateMode)
            putString(KEY_SEPARATE_AUDIO_DIR, appPrefs.separateAudioDir)
            apply()
        }
        _appPrefsFlow.value = appPrefs
    }

    fun resetToDefaults() {
        prefs.edit().clear().apply()
        val defaultPrefs = AppPreferences()
        _appPrefsFlow.value = defaultPrefs
        configFlow.value = defaultPrefs.downloadConfig
        _setupCompletedFlow.value = false
    }

    fun markSetupCompleted() {
        prefs.edit().putBoolean(KEY_SETUP_COMPLETED, true).apply()
        _setupCompletedFlow.value = true
    }

    fun isSetupCompleted(): Boolean = prefs.getBoolean(KEY_SETUP_COMPLETED, false)

    companion object {
        private const val PREFS_NAME = "mizuki_preferences"

        private const val KEY_TYPE = "pref_type"
        private const val KEY_RES = "pref_resolution"
        private const val KEY_AUDIO_FMT = "pref_audio_fmt"
        private const val KEY_EMBED_THUMB = "pref_embed_thumb"
        private const val KEY_EMBED_SUBS = "pref_embed_subs"
        private const val KEY_EMBED_META = "pref_embed_meta"
        private const val KEY_CROP_ARTWORK = "pref_crop_artwork"
        private const val KEY_USE_ARIA2C = "pref_use_aria2c"
        private const val KEY_ARIA2C_CONNS = "pref_aria2c_conns"
        private const val KEY_CUSTOM_ARGS = "pref_custom_args"
        private const val KEY_OUT_TEMPLATE = "pref_out_template"
        private const val KEY_OUT_DIR = "pref_out_dir"
        private const val KEY_COOKIES_PATH = "pref_cookies_path"
        private const val KEY_WIFI_ONLY = "pref_wifi_only"
        private const val KEY_SPONSORBLOCK = "pref_sponsorblock"
        private const val KEY_SPONSORBLOCK_CATS = "pref_sponsorblock_cats"
        private const val KEY_RESTRICT_FILENAMES = "pref_restrict_filenames"
        private const val KEY_DOWNLOAD_ARCHIVE = "pref_download_archive"
        private const val KEY_KEEP_SUB_FILES = "pref_keep_sub_files"
        private const val KEY_PRIVATE_MODE = "pref_private_mode"
        private const val KEY_SEPARATE_AUDIO_DIR = "pref_separate_audio_dir"

        private const val KEY_THEME_MODE = "pref_theme_mode"
        private const val KEY_DYNAMIC_COLOR = "pref_dynamic_color"
        private const val KEY_LANG = "pref_language"
        private const val KEY_VIDEO_CONTAINER = "pref_video_container"
        private const val KEY_VIDEO_CODEC = "pref_video_codec"
        private const val KEY_AUDIO_BITRATE = "pref_audio_bitrate"
        private const val KEY_KEEP_ORIG_AUDIO = "pref_keep_orig_audio"
        private const val KEY_SUB_LANGS = "pref_sub_langs"
        private const val KEY_SUB_FORMAT = "pref_sub_format"
        private const val KEY_AUTO_GEN_SUBS = "pref_auto_gen_subs"
        private const val KEY_MAX_CONCURRENT = "pref_max_concurrent"
        private const val KEY_RATE_LIMIT = "pref_rate_limit"
        private const val KEY_AUTO_RETRY = "pref_auto_retry"
        private const val KEY_RETRY_COUNT = "pref_retry_count"
        private const val KEY_PROXY_URL = "pref_proxy_url"
        private const val KEY_CUSTOM_UA = "pref_custom_ua"
        private const val KEY_EXTRACTOR_ARGS = "pref_extractor_args"
        private const val KEY_FORCE_IPV4 = "pref_force_ipv4"
        private const val KEY_PLAYLIST_SUBFOLDER = "pref_playlist_subfolder"
        private const val KEY_OVERWRITE = "pref_overwrite"
        private const val KEY_VERBOSE_LOG = "pref_verbose_log"
        private const val KEY_UPDATE_CHANNEL = "pref_update_channel"
        private const val KEY_SETUP_COMPLETED = "setup_completed"

        @Volatile
        private var INSTANCE: SettingsRepository? = null

        fun getInstance(context: Context): SettingsRepository {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: SettingsRepository(context.applicationContext).also { INSTANCE = it }
            }
        }
    }
}
